#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               on            \
    window_shadow                float          \
    window_opacity               off            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_animation_duration    0.20            \
    window_border                off             \
    window_border_blur           off            \
    window_border_width          3              \
    active_window_border_color   0xff282828     \
    normal_window_border_color   0xff131313     \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    auto_balance                 off             \
    mouse_modifier               cmd            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    layout                       bsp

yabai -m config external_bar all:26:0

yabai -m rule --add app="Discord"       space=4
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^VLC$" manage=off

echo "yabai configuration loaded.."
