#!/usr/bin/env bash

icon="/usr/share/icons/Papirus-Dark/16x16" 
res=$(echo -en " Reload\0icon\x1f$icon/actions/reload.svg| Lock\0icon\x1f$icon/apps/system-lock-screen.svg| Logout\0icon\x1f$icon/apps/system-log-out.svg| Shutdown\0icon\x1f$icon/apps/system-shutdown.svg| Reboot\0icon\x1f$icon/apps/system-reboot.svg" | rofi -sep "|" -dmenu -i -p 'Power Options' -font "FontAwesome 20" -dpi 92 ) # Make selection prompt
wm=$(wmctrl -m | grep Name | cut -d: -f2)

if [ $res = "Reload" ]; then 

    dunstify 'Reloading config' -a Notification -i /usr/share/icons/Papirus-Dark/16x16/actions/reload.svg 
    sleep 1 

    if [ $wm = "bspwm" ]; then
        sh ~/.config/bspwm/bspwmrc # Reload bspwm
    fi

elif [ $res = "Lock" ]; then 

    dunstify 'Locking screen' -a Notification -i /usr/share/icons/Papirus-Dark/16x16/apps/system-lock-screen.svg 
    sleep 1 
    ~/.bin/lock 

elif [ $res = "Logout" ]; then 

    dunstify 'Logging out' -a Notification -i /usr/share/icons/Papirus-Dark/16x16/apps/system-log-out.svg 
    sleep 1  
    killall Xorg 

elif [ $res = "Shutdown" ]; then 

    dunstify 'Shutting down' -a Notification -i /usr/share/icons/Papirus-Dark/16x16/apps/system-shutdown.svg 
    sleep 1 
    /sbin/systemctl poweroff

elif [ $res = "Reboot" ]; then 

    dunstify 'Rebooting' -a Notification -i /usr/share/icons/Papirus-Dark/16x16/apps/system-reboot.svg 
    sleep 1 
    /sbin/systemctl reboot 

fi

exit 0 
