#! /bin/sh

sxhkd &

killall dunst
killall picom
killall polybar
killall mpd
mpd &
nitrogen --restore &
dunst &
sh $HOME/bin/xob-start &
xsetroot -cursor_name left_ptr &
picom &
sh $HOME/.config/polybar/launch.sh
optimus-manager-qt &

bspc monitor -d "1" "2" "3" "4" "5" "6" "7" "8" "9"

bspc config border_width	3
bspc config focused_border_color "#474545"
bspc config normal_border_color "#272929"
bspc config window_gap		10

# bspc config top_padding 	45
bspc config top padding 0
#bspc config top_padding 0
bspc config bottom_padding	39

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_follows_pointer	true

# bspc rule -a youtubemusic desktop='^8'
bspc rule -a discord desktop='^8'
bspc rule -a "YouTube Music" desktop='^9'


#requires wmutils/opt
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

