#! /bin/sh

sxhkd &

killall dunst
killall picom
killall polybar
nitrogen --restore &
dunst &
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
sh $HOME/.config/polybar/launch.sh
nm-applet &

bspc monitor -d I II III IV V VI 

bspc config border_width	3
#bspc config focused_border_color \#808080
#bspc config normal_border_color \##5a5a5a
bspc config window_gap		5

bspc config top_padding 	30
bspc config bottom_padding	0

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
#bspc config focus_follows_pointer	true

#requires wmutils/opt
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#double borders script 
sh $HOME/.bin/borders
